export HADOOP_OS_TYPE=${HADOOP_OS_TYPE:-$(uname -s)}

export HADOOP_HEAPSIZE="1024"
export HADOOP_NAMENODE_MAX_HEAPSIZE="-Xmx2048m"
export HADOOP_NAMENODE_INIT_HEAPSIZE="-Xms${HADOOP_HEAPSIZE}m"
export HADOOP_DATANODE_MAX_HEAPSIZE="-Xmx2048m"
export HADOOP_DATANODE_INIT_HEAPSIZE="-Xms${HADOOP_HEAPSIZE}m"

export HADOOP_CLIENT_OPTS="-Xmx${HADOOP_HEAPSIZE}m"
export HDFS_NAMENODE_OPTS="-XX:+UseParallelGC $HADOOP_NAMENODE_MAX_HEAPSIZE $HADOOP_NAMENODE_INIT_HEAPSIZE"
export HDFS_DATANODE_OPTS="-XX:+UseParallelGC $HADOOP_DATANODE_MAX_HEAPSIZE $HADOOP_DATANODE_INIT_HEAPSIZE"